name: APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 17
        uses: actions/setup-java@v4.0.0

        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v3.0.0


  package:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - run: mkdir -p path/to/artifact
      - uses: actions/upload-artifact@v4
        with:
          name: meow-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
